// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicLibraryAPI.Data;

#nullable disable

namespace MusicLibraryAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231120211924_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MusicLibraryAPI.Models.Playlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Playlists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Favorite Songs"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dancing Music"
                        });
                });

            modelBuilder.Entity("MusicLibraryAPI.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Like")
                        .HasColumnType("int");

                    b.Property<int?>("PlaylistId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Album = "Un Verano Sin ti",
                            Artist = "Bad Bunny",
                            Genre = "Reggaeton",
                            Like = 0,
                            ReleaseDate = new DateTime(2019, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Callaita"
                        },
                        new
                        {
                            Id = 2,
                            Album = "Un Verano Sin ti",
                            Artist = "Bad Bunny",
                            Genre = "Reggeaton",
                            Like = 0,
                            ReleaseDate = new DateTime(2019, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Moscow Mule"
                        },
                        new
                        {
                            Id = 3,
                            Album = "Un Verano Sin ti",
                            Artist = "Bad Bunny",
                            Genre = "Reggeaton",
                            Like = 0,
                            ReleaseDate = new DateTime(2019, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Titi Me Pregunto"
                        },
                        new
                        {
                            Id = 4,
                            Album = "Un Verano Sin ti",
                            Artist = "Bad Bunny",
                            Genre = "Reggeaton",
                            Like = 0,
                            ReleaseDate = new DateTime(2019, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Después de la Playa"
                        },
                        new
                        {
                            Id = 5,
                            Album = "Un Verano Sin ti",
                            Artist = "Bad Bunny",
                            Genre = "Reggeaton",
                            Like = 0,
                            ReleaseDate = new DateTime(2019, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Me Porto Bonito"
                        },
                        new
                        {
                            Id = 6,
                            Album = "Un Verano Sin ti",
                            Artist = "Bad Bunny",
                            Genre = "Reggeaton",
                            Like = 0,
                            ReleaseDate = new DateTime(2019, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Party"
                        },
                        new
                        {
                            Id = 7,
                            Album = "Un Verano Sin ti",
                            Artist = "Bad Bunny",
                            Genre = "Reggeaton",
                            Like = 0,
                            ReleaseDate = new DateTime(2019, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Neverita"
                        },
                        new
                        {
                            Id = 8,
                            Album = "Un Verano Sin ti",
                            Artist = "Bad Bunny",
                            Genre = "Reggeaton",
                            Like = 0,
                            ReleaseDate = new DateTime(2019, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "El Apagón"
                        },
                        new
                        {
                            Id = 9,
                            Album = "Un Verano Sin ti",
                            Artist = "Bad Bunny",
                            Genre = "Reggeaton",
                            Like = 0,
                            ReleaseDate = new DateTime(2019, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Andrea"
                        },
                        new
                        {
                            Id = 10,
                            Album = "Un Verano Sin ti",
                            Artist = "Bad Bunny",
                            Genre = "Reggeaton",
                            Like = 0,
                            ReleaseDate = new DateTime(2019, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Me Fui de Vacaciones"
                        });
                });

            modelBuilder.Entity("MusicLibraryAPI.Models.Song", b =>
                {
                    b.HasOne("MusicLibraryAPI.Models.Playlist", "playlist")
                        .WithMany("Songs")
                        .HasForeignKey("PlaylistId");

                    b.Navigation("playlist");
                });

            modelBuilder.Entity("MusicLibraryAPI.Models.Playlist", b =>
                {
                    b.Navigation("Songs");
                });
#pragma warning restore 612, 618
        }
    }
}
